In [2]:
import numpy as np
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
dft_result = np.fft.fft2(array)
print(array)
print(dft_result)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 78. +0.j          -6. +6.j          -6. +0.j          -6. -6.j        ]
 [-24.+13.85640646j   0. +0.j           0. +0.j           0. +0.j        ]
 [-24.-13.85640646j   0. +0.j           0. +0.j           0. +0.j        ]]
