In [8]:
import numpy as np
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]) 
dft_result = np.fft.fft2(array)
print(array)
print(dft_result)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[10.+0.j -2.+2.j -2.+0.j -2.-2.j]
 [26.+0.j -2.+2.j -2.+0.j -2.-2.j]
 [42.+0.j -2.+2.j -2.+0.j -2.-2.j]
 [58.+0.j -2.+2.j -2.+0.j -2.-2.j]]
